openapi: 3.0.3
info:
  title: MII Feasibility Backend REST API
  description: todo
  contact:
    email: noreply@todo.de
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 0.0.2
servers:
  - url: https://to.be.defined
    variables:
      basePath:
        default: /api/v2
tags:
  - name: query
    description: CRUD operations for queries
  - name: query content
    description: Operations referring only to the structured query part of a query
  - name: query results
    description: limited CRUD operations for query results (read and update only)
  - name: intrinsics
    description: Offers intrinsic information about this application.
paths:
  /query:
    get:
      tags:
        - query
      summary: Read all your own queries from the broker
      description: This returns all queries you created.
      operationId: listQueries
      security:
        - feasibility_auth:
            - read:query
    post:
      tags:
        - query
      summary: Create a query in the broker
      description: The query will be spawned in the 'created' state and will not be
        published until modified accordingly
      operationId: createQuery
      security:
        - feasibility_auth:
            - write:query
  /query/by-user/{userId}:
    get:
      tags:
        - query
      summary: Finds query summary (id, label, lastModified) of all queries of one user
      description: User identification is done via auth id
      operationId: findQueriesByUser
      security:
        - fdpg_auth:
            - read:all
  /query/{queryId}:
    get:
      tags:
        - query
      summary: Read query by ID
      description: Returns a single query. Contains everything known about the query, including results and structured query
      operationId: getQueryById
      security:
        - feasibility_auth:
            - read:query
    put:
      tags:
        - query
      summary: Update a query in the broker
      description: The query will be updated in the broker. Not sure if this will be allowed at all. If it will be allowed, only in the 'created' state.
      operationId: updateQuery
      security:
        - feasibility_auth:
            - write:query
    delete:
      tags:
        - query
      summary: Deletes a query
      operationId: deleteQuery
      security:
        - feasibility_auth:
            - delete:query
    patch:
      tags:
        - query
      summary: Updates query status
      operationId: updateQueryStatus
      security:
        - feasibility_auth:
            - write:query
  /query/{queryId}/content:
    get:
      tags:
        - query content
      summary: Read structured query of a query by the query id
      description: Returns the structured query of a single query.
      operationId: getQueryContentByQueryId
      security:
        - feasibility_auth:
            - read:query
  /query/{queryId}/result:
    get:
      tags:
        - query results
      summary: Read query result by ID
      description: Returns either your own result for this query
        (if you are authorized by your token) or all results if you got admin rights.
        The query results might also be an aggregated one. This is not decided yet.
      operationId: getQueryResultsByQueryId
      security:
        - feasibility_auth:
            - read:result
            - read:all
    delete:
      tags:
        - query results
      summary: Delete single query result by query and "responder" ID
      description: Delete the response of one site/client for a query
      operationId: deleteQueryResultsByQueryId
      security:
        - feasibility_auth:
            - delete:result
  /actuator/health:
    get:
      summary: Offers health information about this application.
      description: ''
      operationId: ''
      tags:
        - intrinsics
components:
  securitySchemes:
    feasibility_auth:
      type: oauth2
      flows:
        implicit:
          authorizationUrl: http://to.be.defined/auth
          scopes:
            write:query: create and modify queries in your account
            read:query: read your queries
            delete:query: delete your queries
            read:all: read all queries
            delete:all: delete any query
            write:result: write a result for a query/site combination
            read:result: read the results of a query
            delete:result: delete the result of a query
    fdpg_auth:
      type: oauth2
      flows:
        clientCredentials:
          tokenUrl: http://to.be.defined/auth/realms/tbd/protocol/openid-connect/token",
          scopes:
            read:all: read all queries

