openapi: 3.0.3
info:
  title: MII Feasibility Backend REST API
  description: todo
  contact:
    email: noreply@todo.de
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 0.0.2
servers:
  - url: https://to.be.defined
    variables:
      basePath:
        default: /api/v1/query-handler
tags:
  - name: query
    description: operations for queries
  - name: templates
    description: operations to work with query templates
  - name: intrinsics
    description: Offers intrinsic information about this application.
  - name: draft
    description: These endpoints are not yet implemented and are subject to discussion
paths:
  /run-query:
    post:
      tags:
        - query
      summary: Create a query in the broker
      description: The query will be spawned in the broker and directly be dispatched
      operationId: runQuery
      security:
        - feasibility_auth:
            - write:query
  /query/by-user/{userId}:
    get:
      tags:
        - draft
      summary: Finds query summary (id, label, lastModified) of all queries of one user
      description: User identification is done via auth id
      operationId: findQueriesByUser
      security:
        - fdpg_auth:
            - read:all
  /query/{queryId}:
    get:
      tags:
        - draft
      summary: Read query by ID
      description: Returns a single query. Contains everything known about the query, including results and structured query
      operationId: getQueryById
      security:
        - feasibility_auth:
            - read:query
  /query/{queryId}/content:
    get:
      tags:
        - draft
      summary: Read structured query of a query by the query id
      description: Returns the structured query of a single query.
      operationId: getQueryContentByQueryId
      security:
        - feasibility_auth:
            - read:query
  /query/result/{queryId}:
    get:
      tags:
        - query
      summary: Read query result by ID
      description: Returns either your own result for this query
        (if you are authorized by your token) or all results if you got admin rights.
        The query results might also be an aggregated one. This is not decided yet.
      operationId: getQueryResultsByQueryId
      security:
        - feasibility_auth:
            - read:result
            - read:all
  /query/{queryId}/result:
    get:
      tags:
        - draft
      summary: Read query result by ID
      description: Returns either your own result for this query
        (if you are authorized by your token) or all results if you got admin rights.
        The query results might also be an aggregated one. This is not decided yet.
      operationId: getQueryResultsByQueryId2
      security:
        - feasibility_auth:
            - read:result
            - read:all
  /stored-query:
    post:
      tags:
        - templates
      summary: Store a structured query with additional label and comment
      operationId: storeQuery
      security:
        - feasibility_auth:
            - write:query
    get:
      tags:
        - templates
      summary: Read list of stored queries
      description: Returns the list of all queries of the current user
      operationId: getStoredQueryList
      security:
        - feasibility_auth:
            - read:query
  /stored-query/{queryId}:
    get:
      tags:
        - templates
      summary: Read a stored query
      description: Returns he stored query with the given id
      operationId: getStoredQuery
      security:
        - feasibility_auth:
            - read:query
  /stored-query/validate:
    get:
      tags:
        - templates
      summary: Check all own queries for invalid or outdated termcodes
      description: Returns a list of stored queries with the additional info if a query is valid
      operationId: validateStoredQueryList
      security:
        - feasibility_auth:
            - read:query
  /actuator/health:
    get:
      summary: Offers health information about this application.
      description: ''
      operationId: ''
      tags:
        - intrinsics
components:
  securitySchemes:
    feasibility_auth:
      type: oauth2
      flows:
        implicit:
          authorizationUrl: http://to.be.defined/auth
          scopes:
            write:query: create and modify queries in your account
            read:query: read your queries
            delete:query: delete your queries
            read:all: read all queries
            delete:all: delete any query
            write:result: write a result for a query/site combination
            read:result: read the results of a query
            delete:result: delete the result of a query
    fdpg_auth:
      type: oauth2
      flows:
        clientCredentials:
          tokenUrl: http://to.be.defined/auth/realms/tbd/protocol/openid-connect/token",
          scopes:
            read:all: read all queries

